link: item-film.o utils.o film.o videoteca.o list.o main.o
	gcc item-film.o utils.o film.o videoteca.o  list.o main.o -o video.exe
item-film.o:
	gcc -c item-film.c
utils.o:
	gcc -c utils.c
film.o:
	gcc -c film.c
videoteca.o:
	gcc -c videoteca.c
list.o:
	gcc -c list.c
main.o:
	gcc -c main.c
clean:
	rm -f item-film.o  utils.o  film.o  videoteca.o  list.o  main.o  video.exe