link:utils.o item-int.o list.o bst.o main.o
	gcc utils.o item-int.o list.o bst.o main.o -o lista.exe

utils.o:
	gcc -c utils.c
item-int.o:
	gcc -c item-int.c
item-string.o:
	gcc -c item-string.c
list.o:
	gcc -c list.c
bst.o:
	gcc -c bst.c
main.o:
	gcc -c main.c
clean:
	rm -f utils.o item-int.o item-string.o list.o bst.o main.o lista.exe