link : libretto.o esame.o main.o
	gcc libretto.o esame.o main.o -o adtlib.exe
esame.o:
	gcc -c esame.c
libretto.o:
	gcc -c libretto.c
main.o:
	gcc -c main.c
clean:
	rm -f esame.o libretto.o main.o  adtlib.exe