link: automobile.o catalogo.o list.o item-auto.o utils.o main.o
	gcc automobile.o catalogo.o list.o item-auto.o utils.o main.o -o catalogo.exe
automobile.o:
	gcc -c automobile.c
catalogo.o:
	gcc -c catalogo.c
list.o:
	gcc -c list.c
item-auto.o:
	gcc -c item-auto.c
utils.o:
	gcc -c utils.c 
main.o:
	gcc -c main.c
clean:
	rm -f automobile.o catalogo.o list.o item-auto.o utils.o main.o catalogo.exe